language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7

before_install:
- openssl aes-256-cbc -K $encrypted_54cb58de864e_key -iv $encrypted_54cb58de864e_iv
  -in .travis/.deploy.txt.enc -out .travis/.deploy.txt -d

after_success:
- chmod 600 .travis/.deploy.txt
- ssh-add .travis/.deploy.txt
- git remote add deploy ssh://549aeee75973cad4070000fe@tns-forfutureco.rhcloud.com/~/git/tns.git/
- mvn clean install -Popenshift
- git rm -r src pom.xml
- git add webapps
- command -v date && COMMIT="DEPLOYED: `date`" || "DEPLOYED!!!"
- git commit -m "New Deployment: $DATETIME"
- git push deploy --force
