# Site settings
title: TNS | Transport Notification Service
email: we@forfuture.co.ke
description: >
  A Transport Notification Service.
github_username:  forfuture-dev

# Build settings
markdown: kramdown
collections:
  docs:
    output: true
sass:
  style: compressed
