# Site settings
title: TNS | Transport Notification Service
email: we@forfuture.co.ke
description: >
  A Transport Notification Service.
github_username:  forfuture-dev
repository_name: bara
repository_url: https://github.com/forfuture-dev/bara

# Render Settings
baseurl: /bara

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments
collections:
  docs:
    output: true
sass:
  style: compressed
